[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xffa198"
index = 17

[colors.bright]
black = "0x6e7681"
blue = "0x79c0ff"
cyan = "0x39c5cf"
green = "0x56d364"
magenta = "0xd2a8ff"
red = "0xffa198"
white = "0xb3b1ad"
yellow = "0xe3b341"

[colors.normal]
black = "0x484f58"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x3fb950"
magenta = "0xbc8cff"
red = "0xff7b72"
white = "0xb3b1ad"
yellow = "0xd29922"

[colors.primary]
background = "0x0d1117"
foreground = "0xb3b1ad"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[window]
dynamic_padding = false
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
